# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

branches:
  except:
    - T134-v3

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --no-vignettes"

r_packages:
  - xml2

r_github_packages:
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

after_success:
- Rscript -e 'library(covr); codecov()'
